package productabstractions;

public enum Roles {
    SAGSBEHANDLER_GENEREL,
    SAGSBEHANDLER_GODKENDER,
    BETALINGSSAGSBEHANDLER,
    BETALINGSSAGSBEHANDLER_GODKENDER,
    FORDRINGSHAVERSAGSBEHANDLER,
    SE_SAGSBEHANDLER_MED_NOTER,
    FUNKTIONSLEDER,
    SYSTEMADMINISTRATOR,
    VIP_SAGSBEHANDLER;
}
