alter session set "_ORACLE_SCRIPT"=true;
CREATE TABLESPACE CISTS_01 LOGGING DATAFILE '/opt/oracle/oradata/ORCLCDB/cists/cists01.dbf' SIZE 1024M
REUSE AUTOEXTEND ON NEXT 8192K MAXSIZE UNLIMITED EXTENT
MANAGEMENT LOCAL UNIFORM SIZE 1M;

CREATE TABLESPACE opa1 DATAFILE '/opt/oracle/oradata/ORCLCDB/opats/opa1.dbf' SIZE 500M
REUSE AUTOEXTEND ON NEXT 8192K MAXSIZE UNLIMITED EXTENT
MANAGEMENT LOCAL UNIFORM SIZE 1M;
